# Generated by Django 6.0.1 on 2026-01-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_payment_transaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pidx',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('cod', 'Cash on Delivery')], max_length=50),
        ),
    ]
