# Generated by Django 6.0.1 on 2026-01-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('customer', 'CUSTOMER')], default='customer', max_length=20),
        ),
    ]
