# Generated by Django 6.0.1 on 2026-01-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Seller', 'SELLER'), ('customer', 'CUSTOMER')], default='customer', max_length=20),
        ),
    ]
