# Generated by Django 6.0.1 on 2026-01-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_adress_user_address_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
