# Generated by Django 6.0.1 on 2026-01-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='User/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'SELLER'), ('customer', 'CUSTOMER'), ('admin', 'ADMIN')], default='customer', max_length=20),
        ),
    ]
