# Generated by Django 6.0.1 on 2026-01-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_ammount',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('canceled', 'Canceled')], default='pending', max_length=50),
        ),
    ]
