# Generated by Django 6.0.1 on 2026-01-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
    ]
