# Generated by Django 6.0.1 on 2026-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_coupon_users_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
