# Generated by Django 6.0.1 on 2026-01-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
