# Generated by Django 6.0.1 on 2026-01-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_product_created_at_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
