# Generated by Django 6.0.1 on 2026-01-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductSKU/'),
        ),
    ]
