# Generated by Django 6.0.1 on 2026-01-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_category_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skuatrribute',
            unique_together={('sku', 'attribute')},
        ),
    ]
